### PR TITLE
Support delta updates (preliminary implementation)

### PR DESCRIPTION
**Pull request by mherrmann**
Andrey Lisin told me that you were thinking of adding support for delta updates. I had already started working on this. I am sharing my changes with you here. Maybe you will find them to serve as a good starting point for your own implementation.

This implementation is not complete. Almost all tests pass, but the API (`omaha.api`) isn't yet updated to support the new changes. Amazon S3 support also isn't updated. Finally, the migration added in this commit needs to be modified before deployment to not just delete `Version#file`, but to also migrate existing data in that field to `Package#file`.

Here's how I think an implementation of delta updates in `omaha-server` should work:

Currently, each App Version in omaha-server has exactly one "File". For example, say your App is at Version 1.2(.0.0) and you have previous versions 1.0 and 1.1. Then you have the following Files:
- install-1_0.exe
- install-1_1.exe
- install-1_2.exe

I would propose to add a new entry to manage files to the left-hand navigation bar, under "Omaha" below entry "Versions":

image

(I suggest calling this "Packages", because this is the term Omaha uses.)

Instead of uploading the file for a version in the "Versions" interface, you would then upload the file on the "Packages" page.

The difference is that you could upload multiple Packages (=files) per Version. For each Package, you would have to supply the Version it is for, and optionally the base version from which this Package updates. In addition to the files above, you could then for instance upload:
- update-1_0-1_2.exe
- update-1_1-1_2.exe

So this would be two Packages, both for Version 1.2, the first updating clients which are still at version 1.0, the second updating clients that are already at version 1.1.

If the differential update fails for some reason, the update-...exe could set the client-side app version to some bogus value. The next time the Omaha client runs, it would try to find an update-...exe for that bogus version, would fail, and thus download the full install-1_2.exe.

### CODE REVIEW

**Comment by kyakovenko** [comment]
Hello Michael,

Thank you for your pull request! 

Delta updates is a cool feature which can potentially reduce web traffic, by the way S3 isn't really sensitive to traffic load and it can be useful only for in-house solutions. Anyway, we should be careful with making changes in the current business process in order to not hurt other members of the community. At the moment I consider delta updates as an optional feature which should be implemented in a way that it can't affect the current process when one version has one main installer. Packages can be like an alternative for this approach to provide an opportunity to update an application, e.g. 1.2.5 -> 1.2.6 and 1.2.6 -> 1.3, but in the same time we need to have a way to update the whole application, e.g. 1.2.5 -> 1.3. 

We should also remember about partial updates which Omaha-server already supports and implement the same behavior for delta updates.

**Comment by mherrmann** [comment]
Hi Kirill,

thank you for considering the PR (and for your work on `omaha-server` in general).

The way it is currently implemented in the PR is that delta updates are an optional feature from the point of view of the existing code. You can see this in `Version#file`. This is now a `@property` which returns the `file` from the "main Package". The "main Package" is the unique `Package` for which there is no source version (" -> 1.3" - with nothing in front of the "->").

In other words, the PR takes care not to break any existing API.

However, Packages in the PR are not "optional" from the user's point of view (because the UI has changed - users add the "main installer" for a version under "Packages" and not on a Version's page).

The PR has the advantage that it treats packages in the most general way, and in the spirit of Omaha's original documentation. The disadvantage is that it requires the user to know about "packages", even if (s)he does not want to use delta updates.

An alternative implementation could be to use `Package` in the code solely for delta updates, and keep `Version#file`. Then the feature would be truly optional. From a technical perspective, I would still prefer the current implementation from the PR because it is more faithful to Omaha's documentation; But I understand of course that you don't want to break the UI/API for existing users.

Since writing the PR, I realised that `Package#version` should better be a `ForeignKey` to `Version`, rather than a `VersionField`.

What are Partial Updates actually? My impression was that they allow you to roll out new versions to small parts of the user base, for testing. Is that correct?

Cheers!
Michael

**Comment by kyakovenko** [comment]
> An alternative implementation could be to use Packages solely for delta updates, and keep Version#file. Then the feature would be truly optional. From a technical perspective, I would still prefer the current implementation from the PR because it is more faithful to Omaha's documentation; But I understand of course that you don't want to break the UI/API for existing users.

It's still open question. We're looking for a way how we can implement a support of packages in such way that it won't complicate too much Omaha-server and how to do it right in the same time. I'll look at your pull request more fixedly and I'll have a meeting with Andrey Lisin about this issue during this week after that I'll be able to tell something more precisely.

> What are Partial Updates actually? My impression was that they allow you to roll out new versions to small parts of the user base, for testing. Is that correct?

Yes, it's correct. You can find more information about partial updates in the following wiki doc: https://github.com/Crystalnix/omaha-server/wiki/Partial-updates

**Comment by asesh** [comment]
Hello, have you managed to complete this implementation for delta updates? I did try it and as you mentioned, it's not complete yet

**Comment by mherrmann** [comment]
I have not had time to look into it further, so no sorry.

**Pull request closed without merging**
